/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_illinois_sba_camera2raw_Native */

#ifndef _Included_edu_illinois_sba_camera2raw_Native
#define _Included_edu_illinois_sba_camera2raw_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_illinois_sba_camera2raw_Native
 * Method:    saveImageAsCSV
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_edu_illinois_sba_camera2raw_Native_saveImageAsCSV
  (JNIEnv *, jclass, jstring, jobject, jint, jint);

/*
 * Class:     edu_illinois_sba_camera2raw_Native
 * Method:    saveImageAsBin
 * Signature: (Ljava/lang/String;Ljava/nio/ByteBuffer;II)V
 */
JNIEXPORT void JNICALL Java_edu_illinois_sba_camera2raw_Native_saveImageAsBin
  (JNIEnv *, jclass, jstring, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
